name: Update & Retrain

on:
  schedule:
    - cron: "35 12 * * *"   # runs daily at 11:00 UTC (4:30 PM IST)
  workflow_dispatch:         # manual trigger

permissions:
  contents: write   # allow pushing to the repo


jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python update_and_retrain.py

      - name: Commit & Push updated files
        run: |
         git config --global user.name "github-actions"
         git config --global user.email "actions@github.com"
         git add stock_data/ features/ predictions/
         git diff --cached --quiet || git commit -m "Auto update stock data & retrain"
         git push

      - name: Touch app.py to trigger redeploy
        run: |
         echo "# redeploy trigger $(date)" >> app.py
         git add app.py
         git commit -m "Trigger Streamlit redeploy" || echo "No changes"
         git push


